name: Generate Apks

on:
  push:
    branches: [ "v1" ]
  pull_request:
    branches: [ "v1" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: "x64"

      - name: Chmod Gradle
        run: chmod +x ./gradlew

      - name: Build Gradle
        run: ./gradlew build

      - name: Assemble Debug Apks
        run: |
          ./gradlew assembleAndroidDebug
          ./gradlew assembleChromeosDebug

      - name: Assemble Release Apks
        run: |
          ./gradlew assembleAndroidRelease
          ./gradlew assembleChromeosRelease

      - name: Download Apk Signer
        run: curl -L -o uber-apk-signer.jar https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar

      - name: Sign Release Apks
        run: |
          java -jar ./uber-apk-signer.jar --apks ./app/build/outputs/apk/android/release/app-android-release-unsigned.apk
          java -jar ./uber-apk-signer.jar --apks ./app/build/outputs/apk/chromeos/release/app-chromeos-release-unsigned.apk

      - name: Upload Android Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: androidDebug
          path: ./app/build/outputs/apk/android/debug/*.apk

      - name: Upload Android Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: androidRelease
          path: ./app/build/outputs/apk/android/release/*.apk

      - name: Upload Chromeos Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chromeosDebug
          path: ./app/build/outputs/apk/chromeos/debug/*.apk

      - name: Upload Chromeos Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chromeosRelease
          path: ./app/build/outputs/apk/chromeos/release/*.apk

      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: apks
          delete-merged: true