name: Generate Apks

on:
  push:
    branches: [ "v1" ]
  pull_request:
    branches: [ "v1" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: "x64"

      - name: Chmod Gradle
        run: chmod +x ./gradlew

      - name: Build Gradle
        run: ./gradlew build

      - name: Assemble Debug Apk
        run: |
          ./gradlew assembleDebug

      - name: Assemble Release Apk
        run: |
          ./gradlew assembleRelease

      - name: Download Apk Signer
        run: curl -L -o uber-apk-signer.jar https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar

      - name: Sign Release Apks
        run: |
          java -jar ./uber-apk-signer.jar --apks ./app/build/outputs/apk/release/app-exoplayer-release-unsigned.apk

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: ./app/build/outputs/apk/debug/*.apk

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: ./app/build/outputs/apk/release/*.apk

      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: apks
          delete-merged: true