package h.lillie.ytplayer.requests

import android.annotation.SuppressLint
import android.content.Context
import android.net.http.HttpEngine
import android.os.Build
import android.os.ext.SdkExtensions
import androidx.core.net.toUri
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.Response
import org.json.JSONArray
import org.json.JSONObject
import org.schabi.newpipe.extractor.Image
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.StreamInfoItem
import org.schabi.newpipe.extractor.stream.StreamType
import org.schabi.newpipe.extractor.stream.VideoStream
import java.io.File
import java.net.HttpURLConnection
import java.net.URL
import kotlin.time.Duration.Companion.seconds

class Requests {
    suspend fun extractor(context: Context, videoID: String?, searchQuery: String?): Info? = withContext(Dispatchers.IO) {
        if (SdkExtensions.getExtensionVersion(Build.VERSION_CODES.S) >= 7) {
            NewPipe.init(HttpEngineDownloader(context))
        } else {
            NewPipe.init(OkHttpDownloader())
        }
        
        val service = NewPipe.getService(ServiceList.YouTube.serviceId)

        val target: String = if (searchQuery != null) {
            val search = service.getSearchExtractor(searchQuery)
            search.fetchPage()
            search.initialPage.items.filterIsInstance<StreamInfoItem>().first().url
        } else {
            "https://www.youtube.com/watch?v=${videoID}"
        }

        val info = StreamInfo.getInfo(service, target)

        val videoStream: VideoStream = info.videoOnlyStreams.maxWith(
            compareBy<VideoStream> { it.height <= 1080 }
                .thenBy { it.codec.contains("vp9") }
        )

        val audioStream: AudioStream = info.audioStreams.maxWith(
            compareBy<AudioStream> { it.audioTrackType?.name == "ORIGINAL" }
                .thenBy { it.bitrate }
                .thenBy { it.codec.contains("opus") }
        )

        val subtitles = arrayListOf<Info.Subtitles>()
        val subtitlesFilter = info.subtitles.filter { subtitle ->
            !subtitle.isAutoGenerated
        }

        val base: String = buildString {
            append("""
                <?xml version="1.0" encoding="UTF-8"?>
                <MPD xmlns="urn:mpeg:dash:schema:mpd:2011" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" type="static" mediaPresentationDuration="${info.duration.seconds.toIsoString()}" minBufferTime="PT2.0S">
                <Period>
                    <AdaptationSet mimeType="${videoStream.format?.mimeType}" segmentAlignment="true" startWithSAP="1">
                        <Representation id="video" bandwidth="3000000" width="${videoStream.width}" height="${videoStream.height}" codecs="${videoStream.codec}">
                            <BaseURL>${videoStream.url!!.replace("&", "&amp;")}</BaseURL>
                            <SegmentBase indexRange="${videoStream.indexStart}-${videoStream.indexEnd}">
                                <Initialization range="${videoStream.initStart}-${videoStream.initEnd}" />
                            </SegmentBase>
                        </Representation>
                    </AdaptationSet>
                    <AdaptationSet mimeType="${audioStream.format?.mimeType}" segmentAlignment="true" startWithSAP="1">
                        <Representation id="audio" bandwidth="128000" audioSamplingRate="48000" codecs="${audioStream.codec}">
                            <BaseURL>${audioStream.url!!.replace("&", "&amp;")}</BaseURL>
                            <SegmentBase indexRange="${audioStream.indexStart}-${audioStream.indexEnd}">
                                <Initialization range="${audioStream.initStart}-${audioStream.initEnd}" />
                            </SegmentBase>
                        </Representation>
                    </AdaptationSet>
            """.trimIndent())

            append("\n")

            if (subtitlesFilter.isNotEmpty()) {
                subtitlesFilter.forEach { subtitle ->
                    subtitles.add(Info.Subtitles(
                        subtitle.displayLanguageName,
                        subtitle.languageTag
                    ))
                    append("""
                        <AdaptationSet contentType="text" mimeType="${subtitle.format?.mimeType}" lang="${subtitle.languageTag}">
                            <Role schemeIdUri="urn:mpeg:dash:role:2011" value="subtitle" />
                            <Representation id="caption_${subtitle.languageTag}" bandwidth="256">
                                <BaseURL>${subtitle.url!!.replace("&", "&amp;")}</BaseURL>
                            </Representation>
                        </AdaptationSet>
                    """.trimIndent().prependIndent("\t"))
                    append("\n")
                }
            }

            append("""
                    </Period>
                </MPD>
            """.trimIndent())
        }

        val manifest = File(context.filesDir, "manifest.mpd")
        manifest.writeText(base)

        return@withContext Info(
            info.id,
            info.name,
            info.uploaderName,
            info.thumbnails.maxWith(
                compareBy<Image> { it.height }
                    .thenBy { it.width }
            ).url,
            info.streamType == StreamType.LIVE_STREAM || info.streamType == StreamType.AUDIO_LIVE_STREAM,
            videoStream.height > videoStream.width,
            info.viewCount,
            info.likeCount,
            manifest.absolutePath,
            info.hlsUrl.ifEmpty { null },
            videoStream.url!!.toUri().getQueryParameter("expire")!!,
            subtitles.ifEmpty { null }
        )
    }

    suspend fun returnYouTubeDislike(context: Context, videoID: String): Long? = withContext(Dispatchers.IO) {
        val body: String? = if (SdkExtensions.getExtensionVersion(Build.VERSION_CODES.S) >= 7) {
            httpEngineRequest(context, "https://returnyoutubedislikeapi.com/votes?videoId=$videoID")
        } else {
            okHttpRequest("https://returnyoutubedislikeapi.com/votes?videoId=$videoID")
        }

        if (body == null) return@withContext null
        return@withContext JSONObject(body).getLong("dislikes")
    }

    suspend fun sponsorBlock(context: Context, videoID: String): JSONArray? = withContext(Dispatchers.IO) {
        val body: String? = if (SdkExtensions.getExtensionVersion(Build.VERSION_CODES.S) >= 7) {
            httpEngineRequest(context, "https://sponsor.ajay.app/api/skipSegments?videoID=$videoID&category=sponsor")
        } else {
            okHttpRequest("https://sponsor.ajay.app/api/skipSegments?videoID=$videoID&category=sponsor")
        }

        if (body == null) return@withContext null
        return@withContext JSONArray(body)
    }

    @SuppressLint("NewApi")
    private suspend fun httpEngineRequest(context: Context, url: String): String? = withContext(Dispatchers.IO) {
        val httpEngine: HttpEngine = HttpEngine.Builder(context)
            .setEnableHttp2(true)
            .setEnableQuic(true)
            .build()

        val connection: HttpURLConnection = httpEngine.openConnection(URL(url)) as HttpURLConnection
        connection.requestMethod = "GET"

        val responseCode: Int = connection.responseCode
        if (responseCode != 200) {
            connection.disconnect()
            return@withContext null
        }

        val body: String = connection.getInputStream().bufferedReader().use { it.readText() }
        connection.disconnect()
        return@withContext body
    }

    private suspend fun okHttpRequest(url: String): String? = withContext(Dispatchers.IO) {
        val client: OkHttpClient = OkHttpClient.Builder().build()

        val request: Request = Request.Builder()
            .method("GET", null)
            .url(url)
            .build()

        val response: Response = client.newCall(request).execute()
        if (!response.isSuccessful) {
            response.close()
            return@withContext null
        }

        val body: String = response.body.string()
        response.close()
        return@withContext body
    }
}